Blog/web/views.py
from flask import Blueprint, render_template

from back.models import Article

web_blue = Blueprint('web', __name__)


@web_blue.route('/index/')
def index():
    articles = Article.query.limit(10).all()
    return render_template('web/index.html', articles=articles)


@web_blue.route('/info/<int:id>/')
def info(id):
    article = Article.query.get(id)
    return render_template('web/info.html', article=article)

Blog/templates/web/base.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">

    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="keywords" content="Alex个人博客"/>
    <meta name="description" content="Alex's Blog"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
{% block header %}
{% endblock %}

{% block arti %}
{% endblock %}

{% block footer %}
{% endblock %}
</body>
</html>

Blog/templates/web/base_main.html
{% extends 'web/base.html' %}

{% block css %}
    <link href="/static/web/css/base.css" rel="stylesheet">
    <link href="/static/web/css/index.css" rel="stylesheet">
    <link href="/static/web/css/m.css" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="/static/web/js/jquery.min.js"></script>
    <script src="/static/web/js/jquery.easyfader.min.js"></script>

    <script type="text/javascript">
        window.onload = function () {
            var oH2 = document.getElementsByTagName("h2")[0];
            var oUl = document.getElementsByTagName("ul")[0];
            oH2.onclick = function () {
                var style = oUl.style;
                style.display = style.display == "block" ? "none" : "block";
                oH2.className = style.display == "block" ? "open" : ""
            }
        }
    </script>
{% endblock %}

{% block header %}
    <header>
        <div class="topnav">
            <nav>
                <ul>
                    <li><a href="#">网站首页</a></li>
                    <li><a href="#">关于我</a></li>
                    <li><a href="#">模板分享</a></li>
                    <li><a href="#">学无止境</a></li>
                    <li><a href="#">慢生活</a></li>
                    <li><a href="#">博客导航</a></li>
                    <li><a href="#">留言</a></li>
                </ul>
            </nav>
        </div>
    </header>

{% endblock %}
{% block arti %}
    <div id="editor">
        <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
    </div>

    <!-- 注意， 只需要引用 JS，无需引用任何 CSS ！！！-->
    <script type="text/javascript" src="/static/back/js/wangEditor.min.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor = new E('#editor')
        // 或者 var editor = new E( document.getElementById('editor') )
        editor.create()
    </script>
{% endblock %}
{% block footer %}
    <footer>
        <p>Design by <a href="/">Alex的个人博客</a> <a href="/">浙ICP备11002373号-1</a></p>
    </footer>
{% endblock %}

Blog/templates/web/index.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Alex Blog - 个人博客网站</title>
    <meta name="keywords" content="Alex个人博客"/>
    <meta name="description" content="Alex - 一个专注于开源和创新的码农"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/web/css/base.css" rel="stylesheet">
    <link href="/static/web/css/index.css" rel="stylesheet">
    <link href="/static/web/css/m.css" rel="stylesheet">
    <script src="/static/web/js/jquery.min.js"></script>
    <script src="/static/web/js/index.js"></script>
    <script src="/static/web/js/tags.js"></script>
{#    <script src="/static/web/js/common.js"></script>#}
    <script src="/static/web/js/jquery.easyfader.min.js"></script>
    <style type="text/css">
    .cloud {
    pointer-events: none;
}
#tagsList {
	position: relative;

	width: 364px;

	height: 364px;

    left: -40px;
    pointer-events: none;
}

#tagsList a {
	position: absolute;
	top: 0px;
	left: 0px;
	font-family: cursive;
	color: #000331;
	font-weight: bold;
	text-decoration: none;
	padding: 3px 6px;
    pointer-events: auto;
}
#tagsList a:hover {
	color: #ffcd46;
	letter-spacing: 2px;
}
</style>
    <script >
        window.onload = function () {
            var oH2 = document.getElementsByTagName("h2")[0];
            var oUl = document.getElementsByTagName("ul")[0];
            oH2.onclick = function () {
                var style = oUl.style;
                style.display = style.display == "block" ? "none" : "block";
                oH2.className = style.display == "block" ? "open" : ""
            }
        }
        function searchToggle(obj, evt){
        var container = $(obj).closest('.search-wrapper');

        if(!container.hasClass('active')){
              container.addClass('active');
              evt.preventDefault();
        }
        else if(container.hasClass('active') && $(obj).closest('.input-holder').length == 0){
              container.removeClass('active');
              // clear input
              container.find('.search-input').val('');
              // clear and hide result container when we press close
              container.find('.result-container').fadeOut(100, function(){$(this).empty();});
        }
    }

    function submitFn(obj, evt){
        value = $(obj).find('.search-input').val().trim();

        _html = "Yup yup! Your search text sounds like this: ";
        if(!value.length){
            _html = "请输入你要搜索的关键字！";
        }
        else {
            location.href = '/search?keywords=' + value
        }
        $(obj).find('.result-container').html('<span>' + _html + '</span>');
        $(obj).find('.result-container').fadeIn(100);

        evt.preventDefault()
    </script>
</head>
<body>
<header>
    <div>
        <nav>
            <ul>
                <li><a href="#">Alex个人博客</a></li>
                <li><a href="#">Index</a></li>
                <li><a href="#">About Me</a></li>
                <li><a href="#">Share</a></li>
                <li><a href="#">Learn</a></li>
                <li><a href="#">Live</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Gbook</a></li>
            </ul>

        </nav>
    </div>
</header>
<article>
    <div class="banner">
        <div id="sucaihuo" class="fader"><img class="slide" src="/static/web/images/banner02.jpg"> <img class="slide"
                                                                                                       src="/static/web/images/banner01.jpg">
            <img class="slide" src="/static/web/images/banner03.jpg">
            <div class="fader_controls">
                <div class="page prev" data-target="prev">&lsaquo;</div>
                <div class="page next" data-target="next">&rsaquo;</div>
                <ul class="pager_list">
                </ul>
            </div>
        </div>
        <script>
            $(function () {
                $('#sucaihuo').easyFader();
            });
        </script>
    </div>

    <div class="newblogs">
        <h2 class="hometitle">最新文章</h2>
        <ul>
            {% for article in articles %}
                <li>
                    <h3 class="blogtitle">
                        <span>
                            <a href="{{ url_for('web.info',id=article.id) }}" title="css3" class="classname">Alex个人博客</a>
                        </span>
                        <a href="{{ url_for('web.info',id=article.id) }}">{{ article.title }}</a>
                    </h3>
                    <div class="bloginfo">
                        <span class="blogpic">
                            <a href="{{ url_for('web.info',id=article.id) }}">
                                <img src="/static/web/images/t01.jpg"/>
                            </a>
                        </span>
                        <p>{{ article.desc }}</p>
                    </div>
                    <div class="autor">
                        <span class="lm f_l"></span>
                        <span class="dtime f_l">{{ article.create_time }}</span>
                        <span class="viewnum f_l">浏览（<a href="#">1429</a>）</span>
                        <span class="f_r"><a href="{{ url_for('web.info',id=article.id) }}" class="more">阅读原文>></a></span>
                    </div>
                    <div class="line"></div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="rbox">
         <div class="cloud" id="tagsList">
             <h2 class="hometitle" style="left: 50px;">标签云</h2>

            <a href="#" title="Python">Python</a>

            <a href="#" title="爬虫">爬虫</a>

            <a href="#" title="flask">flask</a>

            <a href="#" title="sec">sec</a>

            <a href="#" title="灰帽">灰帽</a>

            <a href="#" title="web安全">web安全</a>

            <a href="#" title="佛系程序员">佛系程序员</a>

            <a href="#" title="wooyun">wooyun</a>

            <a href="#" title="搬砖">搬砖</a>

            <a href="#" title="apt">apt</a>

            <a href="#" title="个人博客">个人博客</a>

            <a href="#" title="web渗透">web渗透</a>

            <a href="#" title="内网渗透">内网渗透</a>

            <a href="#" title="伪黑阔">伪黑阔</a>

            <a href="#" title="黑盒测试">黑盒测试</a>

            <a href="#" title="灰盒测试">灰盒测试</a>

            <a href="#" title="内网apt攻击">内网apt攻击</a>

    </div>

        <div class="links">
            <h2 class="hometitle">友情链接</h2>
            <ul>
                <li><a href="https://github.com/HBGMZ?tab=repositories">Alex Blog</a></li>
                <li><a href="https://github.com/HBGMZ">GitHub</a></li>
                <li><a href="https://gitee.com/HBgmz/events">Gitee</a></li>
                <li><a href="http://106.14.166.3/index/">刘辛锋个人博客</a></li>
                <li><a href="http://www.yangqq.com" >杨青博客</a></li>
            </ul>
        </div>
        <div class="weixin">
            <h2 class="hometitle">官方微信</h2>
            <ul>
                <img src="/static/web/images/wx.jpg">
            </ul>
        </div>
    </div>
</article>
<footer>
    <p>Design by <a href="/">Alex个人博客</a> <a href="/">浙ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

Blog/templates/web/info.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>内容页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
    <meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青"/>
    <meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/web/css/base.css" rel="stylesheet">
    <link href="/static/web/css/info.css" rel="stylesheet">
    <link href="/static/web/css/main.css" rel="stylesheet">
    <link href="/static/web/css/m.css" rel="stylesheet">
    <link href="/static/web/css/index.css" rel="stylesheet">
    <!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
    <script type="text/javascript">
        window.onload = function () {
            var oH2 = document.getElementsByTagName("h2")[0];
            var oUl = document.getElementsByTagName("ul")[0];
            oH2.onclick = function () {
                var style = oUl.style;
                style.display = style.display == "block" ? "none" : "block";
                oH2.className = style.display == "block" ? "open" : ""
            }
        }
        console.log('{{ article.content }}')
    </script>
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="index.html">网站首页</a></li>
            <li><a href="about.html">关于我</a></li>
            <li><a href="share.html">模板分享</a></li>
            <li><a href="list.html">学无止境</a></li>
            <li><a href="list.html">慢生活</a></li>
            <li><a href="link.html">博客导航</a></li>
            <li><a href="gbook.html">留言</a></li>
        </ul>
    </nav>
</header>
<article>

    <div class="infos">
        <div class="newsview">
            <h2 class="intitle">您现在的位置是：<a href="/">网站首页</a>&nbsp;&gt;&nbsp;<a href="/">学无止境</a></h2>
            <h3 class="news_title">{{ article.title }}</h3>
            <div class="news_author"><span class="au01">Alex</span><span
                    class="au02">{{ article.create_time }}</span><span class="au03">共<b>309</b>人围观</span></div>
            <div class="tags"><a href="/">python</a> <a href="/" target="_blank">Redis</a> <a href="/" target="_blank">MWC</a>
                <a href="/" target="_blank">Flask</a> <a href="/" target="_blank">Mysql</a>
            <a href="/" target="_blank">内网渗透</a> <a href="/" target="_blank">灰盒</a></div>
            <div class="news_about"><strong>简介</strong>{{ article.desc }}</div>
            <div class="news_infos">
                <div id="editor"></div>
                <script>
                    var outhtml = '{{ article.content }}'
                    outhtml = outhtml.replace(/&lt;/g, "<")
                    outhtml = outhtml.replace(/&gt;/g, ">")
                    outhtml = outhtml.replace(/&#34;/g, "'")
                    document.getElementById('editor').innerHTML=outhtml
                </script>
            </div>
        </div>
    </div>
    <div class="share">
      <p class="diggit"><a href="javascript:;" data-newsid="44" data-likecount="14"> 很赞哦！ </a>

              (<b id="diggnum">14</b>)

      </p>
      <p class="dasbox"><a href="javascript:void(0)" onClick="dashangToggle()" class="dashang" title="打赏，支持一下">打赏本站</a></p>
      <div class="hide_box"></div>
      <div class="shang_box" onclick="dashangToggle()">
        <div class="shang_tit">
          <p>感谢您的支持，我会继续努力的!</p>
        </div>
        <div class="shang_payimg"> <img src="/static/web/images/alipayimg.jpg" alt="扫码支持" title="扫一扫"> </div>
        <div class="pay_explain">扫码打赏，你说多少就多少</div>
        <div class="shang_payselect">
          <div class="pay_item checked" data-id="alipay"> <span class="radiobox"></span> <span class="pay_logo"><img src="/static/web/images/alipay.jpg" alt="支付宝"></span> </div>
          <div class="pay_item" data-id="weipay"> <span class="radiobox"></span> <span class="pay_logo"><img src="/static/web/images/wetchat.jpg" alt="微信"></span> </div>
        </div>
        <script type="text/javascript">
    $(function(){
    	$(".pay_item").click(function(){
    		$(this).addClass('checked').siblings('.pay_item').removeClass('checked');
    		var dataid=$(this).attr('data-id');
    		$(".shang_payimg img").attr("src","../static/images/"+dataid+"img.jpg");
    		$("#shang_pay_txt").text(dataid=="alipay"?"支付宝":"微信");
    		return false;
    	});
    });
    function dashangToggle(){
    	$(".hide_box").fadeToggle();
    	$(".shang_box").fadeToggle();
    }
    </script>
      </div>
    </div>
    <div class="nextinfo">
        <p>上一篇：<a href="/">传微软将把入门级Surface平板价格下调150美元</a></p>
        <p>下一篇：<a href="/">云南之行――大理洱海一日游</a></p>
    </div>
    <div class="otherlink">
        <h2>相关文章</h2>
        <ul>
            <li><a href="/" title="云南之行――丽江古镇玉龙雪山">云南之行――丽江古镇玉龙雪山</a></li>
            <li><a href="/" title="云南之行――大理洱海一日游">云南之行――大理洱海一日游</a></li>
            <li><a href="/" target="_blank">住在手机里的朋友</a></li>
            <li><a href="/" target="_blank">豪雅手机正式发布! 在法国全手工打造的奢侈品</a></li>
            <li><a href="/" target="_blank">教你怎样用欠费手机拨打电话</a></li>
            <li><a href="/" target="_blank">原来以为，一个人的勇敢是，删掉他的手机号码...</a></li>
        </ul>
    </div>
    <div class="news_pl">
      <h2>文章评论</h2>
      <form action="" class="comment_form" data-newsid="35">
          <textarea placeholder="请发表您的评论,如需站长回复请留下联系方式" class="comment_input"></textarea>
          <input type="submit" name="" value="评 论" class="comment_sub">
      </form>
      <div class="comment_count">
            0条评论
        </div>

        <div class="comment_list_con">

        </div>

</article>
<footer>
    <p>Design by <a href="/">Alex个人博客</a> <a href="/">浙ICP备11002373号-1</a></p>
</footer>
</body>
</html>

Blog/templates/web/pages.html
{%macro my_paginate(pagination,url)%}
<nav>
    <ul class="pagination">
 
        {%if pagination.has_prev%}
        <li class="page-item active"><a class="page-link" href="{{url_for(url,page=pagination.page-1)}}">上一页</a></li>
        {%else%}
        <li class="page-item disabled"><a class="page-link" href="#">上一页</a></li>
        {%endif%}
 
            {%for page in pagination.iter_pages(1,1,3,1)%}
            {%if page%}
                <li class="page-item {%if page==pagination.page%}active{%endif%}"><a class="page-link" href="{{url_for(url,page=page)}}">{{page}}</a></li>
            {%else%}
                <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
            {%endif%}
 
        {%endfor%}
 
        {%if pagination.has_next%}
        <li class="page-item active"><a class="page-link" href="{{url_for(url,page=pagination.page+1)}}">下一页</a></li>
        {%else%}
        <li class="page-item disabled"><a class="page-link" href="#">下一页</a></li>
        {%endif%}
 
    </ul>
</nav>
{%endmacro%}

Blog/templates/web/time.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>棋子个人博客 - 码农直男癌 - 个人博客网站</title>
<meta name="keywords" content="个人博客,棋子个人博客,个人博客模板,7z1" />
<meta name="description" content="棋子个人博客，码农直男癌" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link rel="stylesheet" href="/static/web/css/jquery.pagination.css">
<link href="/static/web/css/m.css" rel="stylesheet">
<link href="/static/web/css/search-form.css" rel="stylesheet">
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/web/js/jquery.easyfader.min.js"></script>
<script src="/static/web/js/scrollReveal.js"></script>
<script src="/static/web/js/common.js"></script>
<script src="/static/web/js/index.js"></script>
<script src="/static/web/js/tags_about.js"></script>
<script type="text/javascript" src="/static/web/js/jquery.pagination.min.js"></script>
<style type="text/css">
#tagsList {
	position: relative;
	width: 364px;
	height: 364px;
    margin: 0 auto;
    top: 60px;
}
#tagsList a {
	position: absolute;
	top: 0px;
	left: 0px;
	font-family: cursive;
	color: black;
	font-weight: bold;
	text-decoration: none;
	padding: 3px 6px;
}
#tagsList a:hover {
	color: #FF0000;
	letter-spacing: 2px;
}
</style>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
<script type="text/javascript">
    function searchToggle(obj, evt){
        var container = $(obj).closest('.search-wrapper');

        if(!container.hasClass('active')){
              container.addClass('active');
              evt.preventDefault();
        }
        else if(container.hasClass('active') && $(obj).closest('.input-holder').length == 0){
              container.removeClass('active');
              // clear input
              container.find('.search-input').val('');
              // clear and hide result container when we press close
              container.find('.result-container').fadeOut(100, function(){$(this).empty();});
        }
    }

    function submitFn(obj, evt){
        value = $(obj).find('.search-input').val().trim();

        _html = "Yup yup! Your search text sounds like this: ";
        if(!value.length){
            _html = "请输入你要搜索的关键字！";
        }
        else {
            location.href = '/search?keywords=' + value
        }
        $(obj).find('.result-container').html('<span>' + _html + '</span>');
        $(obj).find('.result-container').fadeIn(100);

        evt.preventDefault();
    }
</script>
</head>
<body>
<header>
  <!--menu begin 横向下拉菜单-->
  <div class="menu">
    <nav class="nav" id="topnav">
      <h1 class="logo"><a href="">7z&#39;s Blog</a></h1>
      <li><a href="/">Index</a> </li>
      <li><a href="about.html">About Me</a> </li>

        <li data-cid="1"><a href="/">All</a> </li>

        <li data-cid="2"><a href="/">Python</a> </li>

        <li data-cid="3"><a href="/">Bug List</a> </li>

        <li data-cid="4"><a href="/">Other</a> </li>

      <li><a href="time.html">Time</a> </li>
      <li><a href="gbook.html">Guest Book</a> </li>
      <section class="container">
		<form onsubmit="submitFn(this, event);">
            <div class="search-wrapper">
                <div class="input-holder">
                    <input type="text" class="search-input" placeholder="Type to search" />
                    <button class="search-icon" onclick="searchToggle(this, event);"><span></span></button>
                </div>
                <span class="close" onclick="searchToggle(this, event);"></span>
                <div class="result-container">

                </div>
            </div>
        </form>
	</section>
    </nav>
  </div>
  <!--menu end-->
</header>
<div id="tagsList">

    <a href="#" title="Python">Python</a>

    <a href="#" title="爬虫">爬虫</a>

    <a href="#" title="flask">flask</a>

    <a href="#" title="sec">sec</a>

    <a href="#" title="灰帽">灰帽</a>

    <a href="#" title="web安全">web安全</a>

    <a href="#" title="佛系程序员">佛系程序员</a>

    <a href="#" title="wooyun">wooyun</a>

    <a href="#" title="搬砖">搬砖</a>

    <a href="#" title="apt">apt</a>

    <a href="#" title="个人博客">个人博客</a>

    <a href="#" title="web渗透">web渗透</a>

    <a href="#" title="内网渗透">内网渗透</a>

    <a href="#" title="伪黑阔">伪黑阔</a>

    <a href="#" title="黑盒测试">黑盒测试</a>

    <a href="#" title="灰盒测试">灰盒测试</a>

    <a href="#" title="内网apt攻击">内网apt攻击</a>

</div>
<div class="container">
  <h1 class="t_nav"><span>时光飞逝，机会就在我们眼前，何时找到了灵感，就要把握机遇，我们需要智慧和勇气去把握机会。</span><a href="/" class="n1">网站首页</a><a href="/" class="n2">时间轴</a></h1>
  <div class="timebox">
  <ul id="list">

        <li><span>2019-04-07</span><a href="/news/45" title="3行PHP代码进行流量劫持">3行PHP代码进行流量劫持</a></li>

        <li><span>2019-04-06</span><a href="/news/44" title="【首发】绕过某app付费，修改任意用户">【首发】绕过某app付费，修改任意用户</a></li>

        <li><span>2019-04-04</span><a href="/news/43" title="记一次Chrome插件的开发">记一次Chrome插件的开发</a></li>

        <li><span>2019-03-19</span><a href="/news/42" title="Pyinstaller打包selenium去除chromedriver黑框问题解决！！！">Pyinstaller打包selenium去除chromedriver黑框问题解决！！！</a></li>

        <li><span>2019-03-17</span><a href="/news/41" title="Pyinstaller打包PyQt5代码">Pyinstaller打包PyQt5代码</a></li>

        <li><span>2019-03-17</span><a href="/news/40" title="编写第一个程序界面">编写第一个程序界面</a></li>

        <li><span>2019-03-17</span><a href="/news/39" title="pycharm配置 + PyQt5 + QT Design">pycharm配置 + PyQt5 + QT Design</a></li>

        <li><span>2019-01-26</span><a href="/news/38" title="Flask设置ip黑名单">Flask设置ip黑名单</a></li>

        <li><span>2018-11-21</span><a href="/news/37" title="flask-cache报错No module named &#39;flask.ext&#39;">flask-cache报错No module named &#39;flask.ext&#39;</a></li>

        <li><span>2018-11-18</span><a href="/news/36" title="CkPlayer播放器的视频试看功能">CkPlayer播放器的视频试看功能</a></li>

  </ul>
  <div class="box pagelist">
      <div id="pagination" class="page"></div>
  </div>

  <ul id="list2">
  </ul>
  </div>
</div>
<footer>
  <p>Design by <a href="/" target="_blank">棋子个人博客</a> <a href="/">粤ICP备18139747号</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
<script>
    $(function() {
        $("#pagination").pagination({
            currentPage: 1,
            totalPage: 4,
            callback: function(current) {
                window.location = '/time.html?p=' + current
            }
        });
    });
</script>
</body>
</html>