Blog/back/models.py
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(db.Model):
    #定义自增的主键id字段
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    #定义可变长度为10，且唯一的name字段
    username = db.Column(db.String(10), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    is_delete = db.Column(db.Boolean, default=0)
    create_time = db.Column(db.DateTime, default=datetime.now())
    u_arts = db.relationship('Article', backref='user_art')
    u_types = db.relationship('ArticleType', backref='user_type')

    #tablename不写，则表示模型对应的表名称为模型名的小写
    __tablename__ = 'user'

    def save(self):
        db.session.add(self)
        db.session.commit()


class ArticleType(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    at_name = db.Column(db.String(10), unique=True, nullable=False)
    us = db.Column(db.Integer, db.ForeignKey('user.id'))
    arts = db.relationship('Article', backref='art_tp')

    __tablename__ = 'articletype'

    def save(self):
        db.session.add(self)
        db.session.commit()

    def dele(self):
        db.session.delete(self)
        db.session.commit()


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(30), nullable=False)
    desc = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    type = db.Column(db.Integer, db.ForeignKey('articletype.id'))
    us = db.Column(db.Integer, db.ForeignKey('user.id'))

    __tablename__ = 'article'

    def save(self):
        db.session.add(self)
        db.session.commit()

    def dele(self):
        db.session.delete(self)
        db.session.commit()

Blog/back/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash

from back.models import User, Article, ArticleType
from utils.functions import is_login

back_blue = Blueprint('back', __name__)


@back_blue.route('/register/', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('back/register.html')
    elif request.method == 'POST':
        # 获取数据
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        if username and password and password2:
            user = User.query.filter(User.username == username).first()
            if user:
                error = '该账号已注册，请更换账号'
                return render_template('back/register.html', error=error)
            else:
                if password2 == password:
                    # 录入数据
                    user = User()
                    user.username = username
                    user.password = generate_password_hash(password)
                    user.save()
                    return redirect(url_for('back.login'))
                else:
                    error = '两次密码不一致'
                    return render_template('back/register.html', error=error)
        else:
            error = '请填写完整的信息'
            return render_template('back/register.html', error=error)


@back_blue.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('back/login.html')
    elif request.method == 'POST':
        # 获取数据
        username = request.form.get('username')
        password = request.form.get('password')
        if username and password:
            user = User.query.filter(User.username == username).first()
            if not user:
                error = '该账号不存在，请去注册'
                return render_template('back/login.html', error=error)
            elif not check_password_hash(user.password, password):
                error = '密码错误，请修改密码'
                return render_template('back/login.html', error=error)
            else:
                # 账号密码匹配正确，跳转首页
                session['user_id'] = user.id
                return redirect(url_for('back.index'))
        else:
            error = '请填写完整的登录信息'
            return render_template('back/login.html', error=error)


@back_blue.route('/index/')
@is_login
def index():
    arts = Article.query.all()
    art_num = 0
    for art in arts:
        if art.us == session['user_id']:
            art_num += 1
    types = ArticleType.query.all()
    type_num = 0
    for type in types:
        if type.us == session['user_id']:
            type_num += 1
    return render_template('back/index.html', arts=arts, types=types, art_num=art_num, type_num=type_num)


@back_blue.route('/logout/', methods=['GET'])
@is_login
def logout():
    del session['user_id']
    return redirect(url_for('back.login'))


@back_blue.route('/articles_category/', methods=['GET', 'POST'])
@is_login
def articles_category():
    if request.method == 'GET':
        types = ArticleType.query.all()
        num = 0
        for type in types:
            if type.us == session['user_id']:
                num += 1
        return render_template('back/articles_category.html', types=types, num=num)


@back_blue.route('/articles_category_add/', methods=['GET', 'POST'])
@is_login
def articles_category_add():
    if request.method == 'GET':
        return render_template('back/articles_category_add.html')
    elif request.method == 'POST':
        art_type = request.form.get('art_type')
        if art_type:
            articletype = ArticleType.query.filter(ArticleType.at_name == art_type).first()
            if articletype:
                error = '该分类已存在'
                return render_template('back/articles_category_add.html', error=error)
            else:
                # 保存分类信息
                articletype = ArticleType()
                articletype.at_name = art_type
                articletype.us = session['user_id']
                articletype.save()
                return redirect(url_for('back.articles_category'))
        else:
            error = '请填写分类信息'
            return render_template('back/articles_category_add.html', error=error)


@back_blue.route('/del_type/<int:id>/', methods=['GET'])
@is_login
def del_type(id):
    # 删除分类
    atype = ArticleType.query.get(id)
    atype.dele()
    return redirect(url_for('back.articles_category'))


@back_blue.route('/articles_list/', methods=['GET'])
@is_login
def articles_list():
    arts = Article.query.all()
    num = 0
    for art in arts:
        if art.us == session['user_id']:
            num += 1
    return render_template('back/articles_list.html', arts=arts, num=num)


@back_blue.route('/articles_list_add/', methods=['GET', 'POST'])
@is_login
def articles_list_add():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/articles_list_add.html', types=types)
    elif request.method == 'POST':
        title = request.form.get('title')
        desc = request.form.get('desc')
        content = request.form.get('content')
        type = request.form.get('category')
        us = session['user_id']
        if title and desc and content and type:
            # 保存
            art = Article()
            art.title = title
            art.desc = desc
            art.content = content
            art.type = type
            art.us = us
            art.save()
            return redirect(url_for('back.articles_list'))
        else:
            error = '请填写完整的文章信息'
            types = ArticleType.query.all()
            return render_template('back/articles_list_add.html', error=error, types=types)


@back_blue.route('/del_art/<int:id>/', methods=['GET'])
@is_login
def del_art(id):
    # 删除文章
    article = Article.query.get(id)
    article.dele()
    return redirect(url_for('back.articles_list'))


@back_blue.route('/alter_art/<int:id>/', methods=['GET', 'POST'])
@is_login
def alter_art(id):
    article = Article.query.get(id)
    types = ArticleType.query.all()
    if request.method == 'GET':
        # 修改文章
        return render_template('/back/articles_list_alter.html', article=article, types=types)
    elif request.method == 'POST':
        title = request.form.get('title')
        desc = request.form.get('desc')
        content = request.form.get('content')
        type = request.form.get('category')
        us = session['user_id']
        if title and desc and content and type:
            # 保存
            article.title = title
            article.desc = desc
            article.content = content
            article.type = type
            article.us = us
            article.save()
            return redirect(url_for('back.articles_list'))
        else:
            error = '请填写完整的文章信息'
            return render_template('back/articles_list_alter.html', error=error, article=article, types=types)


@back_blue.route('user_settings', methods=['GET', 'POST'])
@is_login
def user_settings():
    if request.method == 'GET':
        return render_template('back/user_settings.html')
    elif request.method == 'POST':
        return redirect(url_for('back.index'))


@back_blue.route('change_password', methods=['GET', 'POST'])
@is_login
def change_password():
    if request.method == 'GET':
        return render_template('back/change_password.html')
    elif request.method == 'POST':
        password = request.form.get('password')
        con_password = request.form.get('con_password')
        if password and con_password:
            return redirect(url_for('back.index'))
        else:
            error = '请填写完整的密码信息'
            return render_template('back/change_password.html', error=error)

Blog/web/views.py
from flask import Blueprint, render_template

from back.models import Article

web_blue = Blueprint('web', __name__)


@web_blue.route('/index/')
def index():
    articles = Article.query.limit(10).all()
    return render_template('web/index.html', articles=articles)


@web_blue.route('/info/<int:id>/')
def info(id):
    article = Article.query.get(id)
    return render_template('web/info.html', article=article)

Blog/templates/back/articles_category.html
{% extends 'back/base_main.html' %}

{% block title %}
    后台——文章分类
{% endblock %}

{% block main_panel %}
    <div class="main-panel">
        <div class="content">
            <div class="card-header" style="font-size: 18px">
                分类列表
                <a class="btn btn-info" style="float: right;"
                   href="{{ url_for('back.articles_category_add') }}">添加分类</a>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">分类</th>
                        <th scope="col">删除</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for type in types %}
                        <tr>
                            <td>{{ type.at_name }}</td>
                            <td>
                                <a href="{{ url_for('back.del_type',id=type.id) }}" class="la la-times"></a>
                            </td>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block art_type %}
    {{ num }}
{% endblock %}

{% block ac_type %}
    active
{% endblock %}

Blog/templates/back/articles_category_add.html
{% extends 'back/base_main.html' %}

{% block title %}
    后台——添加分类
{% endblock %}

{% block main_panel %}
    <div class="main-panel">
        <div class="content">
            <div class="card-header" style="font-size: 18px">
                分类
                <a class="btn btn-info" style="float: right;"
                   href="{{ url_for('back.articles_category') }}">返回</a>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    <div class="form-group">
                        <label style="font-size: 16px">分类名称：</label>
                        <input class="form-control" id="inlineinput" placeholder="分类..." name="art_type">
                        <small id="emailHelp" style="color: red">{{ error }}</small>
                    </div>
                    <div class="card-action">
                        <input type="submit" class="btn btn-success">
{#                        <button class="btn btn-danger">取消</button>#}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Blog/templates/back/articles_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    后台——文章列表
{% endblock %}

{% block main_panel %}
    <div class="main-panel">
        <div class="content">
            <div class="card-header" style="font-size: 18px">
                文章列表
                <a class="btn btn-info" style="float: right;"
                   href="{{ url_for('back.articles_list_add') }}">添加文章</a>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">文章标题</th>
                        <th scope="col">文章分类</th>
                        <th scope="col">创建时间</th>
                        <th scope="col">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for art in arts %}
                        {% if art.us == session['user_id'] %}
                            <tr>
                                <td>{{ art.title }}</td>
                                <td>{{ art.art_tp.at_name }}</td>
                                <td>{{ art.create_time }}</td>
                                <td>
                                    <a href="{{ url_for('back.alter_art',id=art.id) }}" class="la la-edit"></a>
                                    <a href="{{ url_for('back.del_art',id=art.id) }}" class="la la-times"></a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block art_list %}
    {{ num }}
{% endblock %}

{% block ac_list %}
    active
{% endblock %}

Blog/templates/back/articles_list_add.html
{% extends 'back/base_main.html' %}

{% block title %}
    后台——添加文章
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="/static/back/js/wangEditor.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor = new E('#div1')
        var $text1 = $('#text1')
        editor.customConfig.onchange = function (html) {
            // 监控变化，同步更新到 textarea
            $text1.val(html)
        }
        editor.create()
        // 初始化 textarea 的值
        $text1.val(editor.txt.html())
    </script>
{% endblock %}

{% block main_panel %}
    <div class="main-panel">
        <div class="content">
            <div class="card-header" style="font-size: 18px">
                文章
                <a class="btn btn-info" style="float: right;"
                   href="{{ url_for('back.articles_list') }}">返回</a>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    <div class="form-group form-inline">
                        <label for="inlineinput" class="col-form-label">文章标题：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control input-full" id="inlineinput" name="title"
                                   placeholder="文章标题...">
                        </div>
                    </div>
                    <div class="form-group form-inline">
                        <label for="inlineinput" class="col-form-label">文章描述：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control input-full" id="inlineinput" name="desc"
                                   placeholder="文章描述...">
                        </div>
                    </div>
                    <div class="form-group form-inline">
                        <label for="inlineinput" class="col-form-label">文章分类：</label>
                        <div class="col-md-9">
                            <select class="form-control input-full" id="defaultSelect" name="category">
                                {% for type in types %}
                                    <option value="{{ type.id }}">{{ type.at_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inlineinput" class="col-form-label">文章详情：</label>
                        <div id="div1"></div>
                        <textarea id="text1" style="display:none" name="content"></textarea>
                        <small id="emailHelp" style="color: red">{{ error }}</small>
                    </div>
                    <div class="card-action">
                        <input type="submit" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Blog/templates/back/articles_list_alter.html
{% extends 'back/base_main.html' %}

{% block title %}
    后台——修改文章
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="/static/back/js/wangEditor.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor = new E('#div1')
        var $text1 = $('#text1')
        editor.customConfig.onchange = function (html) {
            // 监控变化，同步更新到 textarea
            $text1.val(html)
        }
        editor.create()
        // 初始化 textarea 的值
        $text1.val(editor.txt.html())
        var outhtml = '{{ article.content }}'
        outhtml = outhtml.replace(/&lt;/g, "<")
        outhtml = outhtml.replace(/&gt;/g, ">")
        outhtml = outhtml.replace(/&#34;/g, "'")
        editor.txt.html(outhtml)
    </script>
{% endblock %}

{% block main_panel %}
    <div class="main-panel">
        <div class="content">
            <div class="card-header" style="font-size: 18px">
                文章
                <a class="btn btn-info" style="float: right;"
                   href="{{ url_for('back.articles_list') }}">返回</a>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    <div class="form-group form-inline">
                        <label for="inlineinput" class="col-form-label">文章标题：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control input-full" id="inlineinput" name="title"
                                   placeholder="文章标题..." value="{{ article.title }}">
                        </div>
                    </div>
                    <div class="form-group form-inline">
                        <label for="inlineinput" class="col-form-label">文章描述：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control input-full" id="inlineinput" name="desc"
                                   placeholder="文章描述..." value="{{ article.desc }}">
                        </div>
                    </div>
                    <div class="form-group form-inline">
                        <label for="inlineinput" class="col-form-label">文章分类：</label>
                        <div class="col-md-9">
                            <select class="form-control input-full" id="defaultSelect" name="category">
                                {% for type in types %}
                                    {% if article.type == type.id %}
                                        <option value="{{ type.id }}" selected="selected">{{ type.at_name }}</option>
                                    {% else %}
                                        <option value="{{ type.id }}">{{ type.at_name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inlineinput" class="col-form-label">文章详情：</label>
                        <div id="div1"></div>
                        <textarea id="text1" style="display:none" name="content"></textarea>
                        <small id="emailHelp" style="color: red">{{ error }}</small>
                    </div>
                    <div class="card-action">
                        <input type="submit" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Blog/templates/back/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
</head>
<body>
    {% block main_header %}
    {% endblock %}

    {% block sidebar %}
    {% endblock %}

    {% block main_panel %}
    {% endblock %}
</body>
{% block js %}
{% endblock %}
</html>

Blog/templates/back/base_main.html
{% extends 'back/base.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/back/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="/static/back/css/ready.css">
    <link rel="stylesheet" href="/static/back/css/demo.css">
{% endblock %}

{% block main_header %}
    <div class="main-header">
        <div class="logo-header">
            <i class="la la-home"></i>
            <a href="{{ url_for('web.index') }}" class="logo">
                网站站点首页
            </a>
            <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse"
                    data-target="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <button class="topbar-toggler more"><i class="la la-ellipsis-v"></i></button>
        </div>
        <nav class="navbar navbar-header navbar-expand-lg">
            <div class="container-fluid">

                <form class="navbar-left navbar-form nav-search mr-md-3" action="">
                    <div class="input-group">
                        <input type="text" placeholder="搜索 ..." class="form-control">
                        <div class="input-group-append">
								<span class="input-group-text">
									<i class="la la-search search-icon"></i>
								</span>
                        </div>
                    </div>
                </form>
                <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                    <li class="nav-item dropdown hidden-caret">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="la la-github"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="http://106.14.166.3/index/">我的hexo博客</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="https://github.com/HBGMZ">我的GitHub</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                            <img src="/static/back/img/profile.png" alt="user-img" width="36" class="img-circle">
                            <span>Alex</span>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <div class="user-box">
                                    <div class="u-img"><img src="/static/back/img/profile.png" alt="user"></div>
                                    <div class="u-text">
                                        <h4>Alex</h4>
                                        <p class="text-muted">2423987316@qq.com</p>
                                        <a href="{{ url_for('back.user_settings') }}"
                                           class="btn btn-rounded btn-danger btn-sm">用户设置</a>
                                    </div>
                                </div>
                            </li>
                            <div class="dropdown-divider"></div>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('back.change_password') }}">
                                <i class="ti-settings"></i>修改密码</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('back.logout') }}"><i class="fa fa-power-off"></i>
                                退出登录</a>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
{% endblock %}

{% block sidebar %}
    <div class="sidebar">
        <div class="scrollbar-inner sidebar-wrapper">
            <ul class="nav">
                <li class="nav-item {% block ac_index %}{% endblock %}">
                    <a href="{{ url_for('back.index') }}">
                        <i class="la la-dashboard"></i>
                        <p>技术支持</p>
                    </a>
                </li>
                <li class="nav-item {% block ac_type %}{% endblock %}">
                    <a href="{{ url_for('back.articles_category') }}">
                        <i class="la la-table"></i>
                        <p>文章分类</p>
                        <span class="badge badge-count">{% block art_type %}{% endblock %}</span>
                    </a>
                </li>
                <li class="nav-item {% block ac_list %}{% endblock %}">
                    <a href="{{ url_for('back.articles_list') }}">
                        <i class="la la-keyboard-o"></i>
                        <p>文章列表</p>
                        <span class="badge badge-count">{% block art_list %}{% endblock %}</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block main_panel %}
{% endblock %}

{% block js %}
    <script src="/static/back/js/core/jquery.3.2.1.min.js"></script>
    <script src="/static/back/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
    <script src="/static/back/js/core/popper.min.js"></script>
    <script src="/static/back/js/core/bootstrap.min.js"></script>
    <script src="/static/back/js/plugin/chartist/chartist.min.js"></script>
    <script src="/static/back/js/plugin/chartist/plugin/chartist-plugin-tooltip.min.js"></script>
    <script src="/static/back/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
    <script src="/static/back/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
    <script src="/static/back/js/plugin/jquery-mapael/jquery.mapael.min.js"></script>
    <script src="/static/back/js/plugin/jquery-mapael/maps/world_countries.min.js"></script>
    <script src="/static/back/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
    <script src="/static/back/js/ready.min.js"></script>
    <script src="/static/back/js/demo.js"></script>
{% endblock %}

Blog/templates/back/change_password.html
{% extends 'back/base_main.html' %}

{% block title %}
    后台——修改密码
{% endblock %}

{% block main_panel %}
    <div class="main-panel">
        <div class="content">
            <div class="card-header" style="font-size: 18px">
                修改密码
                <a class="btn btn-info" style="float: right;"
                   href="{{ url_for('back.articles_list') }}">返回</a>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    <div class="form-group">
                        <label>密码：</label>
                        <input class="form-control" id="inlineinput" placeholder="密码..." name="password">
                    </div>
                    <div class="form-group">
                        <label>确认密码：</label>
                        <input class="form-control" id="inlineinput" placeholder="确认密码..." name="con_password">
                        <small id="emailHelp" style="color: red">{{ error }}</small>
                    </div>
                    <div class="card-action">
                        <input type="submit" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Blog/templates/back/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>用户登录</title>

    <link rel="stylesheet" type="text/css" href="/static/back/css/style.css">

    <script type="text/javascript" src="/static/back/js/jquery.min.js"></script>
    <script type="text/javascript" src="/static/back/js/vector.js"></script>

</head>
<body>

<div id="container">
    <div id="output">
        <div class="containerT">
            <h1>用户登录</h1>
            <form class="form" id="entry_form" method="post">
                <font color="red">{{ error }}</font>
                <input type="text" name="username" placeholder="用户名" id="entry_name">
                <input type="password" name="password" placeholder="密码" id="entry_password">
                <button type="submit" id="entry_btn">登录</button>
                <div id="prompt" class="prompt"></div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        Victor("container", "output");   //登陆背景函数
        $("#entry_name").focus();
        $(document).keydown(function (event) {
            if (event.keyCode == 13) {
                $("#entry_btn").click();
            }
        });
    });
</script>

</body>
</html>